"""agent.prompt_builder stub — type declarations for the host runtime module."""

from typing import Any

def build_system_prompt(skill_name: str, **kwargs: Any) -> str: ...
def build_user_prompt(skill_name: str, **kwargs: Any) -> str: ...
def clear_skills_system_prompt_cache() -> None: ...
