"""agent.skill_utils stub — type declarations for the host runtime module."""

from pathlib import Path
from typing import Any

MAX_DESCRIPTION_LENGTH: int

def extract_skill_description(text: str) -> str: ...
def parse_skill_md(path: str) -> dict[str, Any]: ...
def parse_frontmatter(text: str) -> tuple[dict[str, Any], str]: ...
def get_disabled_skill_names() -> list[str]: ...
def disabled_skills_path() -> Path: ...
