"""Migration note index renderer.

Split from ``_patcher_migration_render.py`` to keep module member count
under wemake's WPS202 threshold. Renders the top-level
``MIGRATION.skill-port.md`` index, including the metadata table,
documents list, and apply steps.
"""

from __future__ import annotations

from hermes_skill_creator_plugin._patcher_migration_consts import LF
from hermes_skill_creator_plugin._patcher_migration_render import _yes_no


def _render_migration_index(timestamp: str) -> str:
    header = _render_index_header(timestamp)
    docs = _render_documents_list()
    apply_steps = _render_apply_steps()
    return f"{header}{LF}{LF}{docs}{LF}{LF}{apply_steps}{LF}"


def _render_index_header(timestamp: str) -> str:
    title = "# Migration Note — Hermes Skill-Creator Plugin"
    comment = (
        "<!-- generated by hermes-skill-creator-patch --emit-migration-note; "
        "do not edit by hand -->"
    )
    rows = [
        "| Field | Value |",
        "| --- | --- |",
        "| Source repo | https://github.com/anthropics/claude-plugins-official |",
        "| Source skillId | skill-creator |",
        "| Pinned upstream commit | TBD |",
        "| Plugin version | 0.1.0 |",
        f"| Generated at | {timestamp} |",
    ]
    table = LF.join(rows)
    return f"{title}{LF}{LF}{comment}{LF}{LF}{table}"


def _render_documents_list() -> str:
    heading = "## Documents in this set"
    doc_lines = [
        "- `MIGRATION.hermes-patch.md` — Script #1 patches "
        "(cap raise + 7 Task E sites).",
        "- `MIGRATION.skill-port.md` — migrated skill bindings (T3 inventory).",
    ]
    joined = LF.join(doc_lines)
    return f"{heading}{LF}{LF}{joined}"


def _render_apply_steps() -> str:
    heading = "## How to apply"
    step1 = (
        "1. Run Script #1 against your user-owned Hermes checkout:\n"
        "   `uv run hermes-skill-creator-patch --apply --task-e-redirect "
        "--target <hermes-checkout>`"
    )
    step2 = "2. Run Script #1 with `--emit-migration-note` to regenerate this file."
    return f"{heading}{LF}{LF}{step1}{LF}{step2}"