"""Skill installer migration-note renderer for ``MIGRATION.skill-port.md``.

Extracted from :mod:`.skill_installer` to keep the installer under
wemake WPS202 (module members <= 7). Renders the markdown body from
the T3 inventory and emits it to the worktree root.

Reference: docs/plans/07-skill-creator-migration.md.
"""

from __future__ import annotations

import os
from datetime import UTC, datetime
from pathlib import Path

from hermes_skill_creator_plugin._patcher_migration_decisions import (
    skill_port_decisions_lines,
)
from hermes_skill_creator_plugin._skill_installer_consts import (
    FROZEN_TIME_ENV_KEY,
    KEY_CLAUDE,
    KEY_HERMES,
    KEY_ID,
    KEY_LOCATION,
    MIGRATION_NOTE_NAME,
    PINNED_UPSTREAM_COMMIT,
    TEXT_ENCODING,
)
from hermes_skill_creator_plugin._skill_installer_note_rows import _render_strength_rows
from hermes_skill_creator_plugin._skill_installer_t3 import T3_INVENTORY


def _format_t3_row(index: int, row: dict[str, str]) -> str:
    """Render one T3 inventory row as a markdown table line."""
    return _T3_ROW_TEMPLATE.format(
        index=index,
        location=row[KEY_LOCATION],
        claude=row[KEY_CLAUDE],
        hermes=row[KEY_HERMES],
        test_id=row[KEY_ID],
    )


_T3_ROW_TEMPLATE = "| {index} | {location} | `{claude}` | `{hermes}` | {test_id} |"


def render_migration_skill_port(
    *,
    generated_at: str,
    upstream_commit: str,
) -> str:
    """Render the body of ``MIGRATION.skill-port.md`` from the T3 inventory."""
    lines: list[str] = [
        "# Skill Port — Migrated skill-creator (T3 inventory)",
        "",
        "<!-- DO NOT EDIT: generated by hermes-skill-creator-plugin -->",
        "",
        "| Field | Value |",
        "| --- | --- |",
        "| Source skill | skill-creator |",
        f"| Pinned upstream commit | {upstream_commit} |",
        "| Hermes nesting-guard var | HERMES_SESSION |",
        f"| Generated at | {generated_at} |",
        "",
        "## Per-binding replacements (T3)",
        "",
        "| # | location | claude-binding | hermes-binding | test-id |",
        "| --- | --- | --- | --- | --- |",
    ]
    for index, row in enumerate(T3_INVENTORY, start=1):
        lines.append(_format_t3_row(index, row))
    lines.extend(_render_strength_rows())
    lines.extend(_render_decisions_section())
    return "\n".join(lines)


def _render_decisions_section() -> list[str]:
    """Render the Decisions section as markdown lines."""
    return skill_port_decisions_lines()


def generated_at() -> str:
    frozen = os.environ.get(FROZEN_TIME_ENV_KEY)
    if frozen:
        return frozen
    return datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")


def write_migration_note(worktree_root: Path) -> Path:
    note = worktree_root / MIGRATION_NOTE_NAME
    note.write_text(
        render_migration_skill_port(
            generated_at=generated_at(),
            upstream_commit=PINNED_UPSTREAM_COMMIT,
        ),
        encoding=TEXT_ENCODING,
    )
    refresh_migration_manifest(worktree_root)
    return note


def refresh_migration_manifest(worktree_root: Path) -> None:
    """Recompute ``.migration_manifest.json`` for every MIGRATION*.md in root.

    Both regeneration paths (Script #1 ``--emit-migration-note`` via
    :func:`hermes_skill_creator_plugin._patcher_migration.generate_migration_note`
    and the migrated-skill installer via :func:`write_migration_note`)
    call this helper so the manifest entry tracks the just-written files
    byte-for-byte. Required by :mod:`tools.check_migration_note` (the
    ``check-migration-note`` pre-commit hook).
    """
    from tools._migration_manifest import dump_manifest
    from tools._migration_paths import GLOB_PATTERNS, sha256_of

    entries: list[tuple[str, str]] = []
    for pattern in GLOB_PATTERNS:
        candidate = worktree_root / pattern
        if candidate.exists():
            entries.append((pattern, sha256_of(candidate)))
    dump_manifest(worktree_root / ".migration_manifest.json", entries)
