"""Skill installer migration-note renderer for ``MIGRATION.skill-port.md``.

Extracted from :mod:`.skill_installer` to keep the installer under
wemake WPS202 (module members <= 7). Renders the markdown body from
the T3 inventory and emits it to the worktree root.

Reference: docs/plans/07-skill-creator-migration.md.
"""

from __future__ import annotations

import os
from datetime import UTC, datetime
from pathlib import Path

from hermes_skill_creator_plugin._skill_installer_consts import (
    FROZEN_TIME_ENV_KEY,
    KEY_CLAUDE,
    KEY_HERMES,
    KEY_ID,
    KEY_LOCATION,
    MIGRATION_NOTE_NAME,
    PINNED_UPSTREAM_COMMIT,
    TEXT_ENCODING,
)
from hermes_skill_creator_plugin._skill_installer_t3 import T3_INVENTORY


def _format_t3_row(index: int, row: dict[str, str]) -> str:
    return f"| {index} | {row[KEY_LOCATION]} | `{row[KEY_CLAUDE]}` | `{row[KEY_HERMES]}` | {row[KEY_ID]} |"


def _render_strength_rows() -> list[str]:
    return [
        "",
        "## Strength preservation",
        "",
        "| Strength | Artifact | Hermes equivalent | AC |",
        "| --- | --- | --- | --- |",
        ("| Subagent split | agents/{grader,analyzer,comparator}.md | delegate_task + agent_name | T3.012-T3.014 |"),
        (
            "| Eval pipeline | "
            "scripts/{run_eval, aggregate_benchmark, "
            "generate_report, ...}.py |"
            " same scripts, Hermes CLI, event-shape adapter |"
            " T3.003, T3.011, T3.006 |"
        ),
        (
            "| Eval viewer | eval-viewer/{generate_review.py, viewer.html} |"
            " generate_review.py --static, file:// URL | T3.015 |"
        ),
        "",
    ]


def render_migration_skill_port(
    *,
    generated_at: str,
    upstream_commit: str,
) -> str:
    """Render the body of ``MIGRATION.skill-port.md`` from the T3 inventory."""
    lines: list[str] = [
        "# Skill Port — Migrated skill-creator (T3 inventory)",
        "",
        "<!-- DO NOT EDIT: generated by hermes-skill-creator-plugin -->",
        "",
        "| Field | Value |",
        "| --- | --- |",
        "| Source skill | skill-creator |",
        f"| Pinned upstream commit | {upstream_commit} |",
        "| Hermes nesting-guard var | HERMES_SESSION |",
        f"| Generated at | {generated_at} |",
        "",
        "## Per-binding replacements (T3)",
        "",
        "| # | location | claude-binding | hermes-binding | test-id |",
        "| --- | --- | --- | --- | --- |",
    ]
    for index, row in enumerate(T3_INVENTORY, start=1):
        lines.append(_format_t3_row(index, row))
    lines.extend(_render_strength_rows())
    return "\n".join(lines)


def generated_at() -> str:
    frozen = os.environ.get(FROZEN_TIME_ENV_KEY)
    if frozen:
        return frozen
    return datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")


def write_migration_note(worktree_root: Path) -> Path:
    note = worktree_root / MIGRATION_NOTE_NAME
    note.write_text(
        render_migration_skill_port(
            generated_at=generated_at(),
            upstream_commit=PINNED_UPSTREAM_COMMIT,
        ),
        encoding=TEXT_ENCODING,
    )
    return note


__all__ = [
    "render_migration_skill_port",
    "generated_at",
    "write_migration_note",
]
