"""hermes_cli.config stub — type declarations for the host runtime module."""

from pathlib import Path
from typing import Any

def get_hermes_home() -> Path: ...
def get_skill_dir() -> Path: ...
def load_config() -> dict[str, Any]: ...
def save_config(config: dict[str, Any]) -> None: ...
