"""hermes_cli.skills_config stub — type declarations for the host runtime module."""

from pathlib import Path
from typing import Any

def load_skill_config(skill_name: str) -> dict[str, Any]: ...
def skill_path(skill_name: str) -> Path: ...
def save_disabled_skills(disabled: list[str]) -> None: ...
