"""hermes_constants stub — type declarations for the host runtime module."""

from pathlib import Path

HERMES_HOME: str
HERMES_SESSION_VAR: str
HERMES_OVERRIDE_VAR: str

def get_hermes_home_override() -> str | None: ...
def set_hermes_home_override(value: str) -> object: ...
def reset_hermes_home_override(token: object) -> None: ...
def resolve_hermes_home() -> Path: ...
