"""_migration_paths.py — paths, patterns, and marker constants."""

from __future__ import annotations

import hashlib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_MANIFEST_NAME = ".migration_manifest.json"
_MARKER_PREFIX = "<!-- DO NOT EDIT"
_MARKER_SUFFIX = ": generated by hermes-skill-creator-plugin -->"
GENERATED_MARKER = _MARKER_PREFIX + _MARKER_SUFFIX
GLOB_PATTERNS = (
    "MIGRATION.md",
    "MIGRATION.hermes-patch.md",
    "MIGRATION.skill-port.md",
)
SHA_PREVIEW_LEN = 12  # magic number: chars shown in human messages.


def sha256_of(path: Path) -> str:
    """Return the hex sha256 of ``path``'s bytes."""
    return hashlib.sha256(path.read_bytes()).hexdigest()
