"""check_migration_note.py — MIGRATION*.md files are generated, not hand-edited.

Pre-commit refuses any MIGRATION*.md whose sha256 differs from the
generator's last-emitted checksum recorded in `.migration_manifest.json`
at the worktree root. The generator (Script #1 --emit-migration-note and
the migrated-skill installer) writes BOTH the MIGRATION*.md file AND the
manifest entry on every regeneration. If a developer hand-edits the
migration note, the checksum drift is caught at commit time.

TDD test cases (mirror of tests/meta/test_meta_check_migration_note.py):

  test_unmodified_migration_file_passes
  test_hand_edit_to_migration_hermes_patch_md_fails
  test_hand_edit_to_migration_skill_port_md_fails
  test_generated_marker_present_passes
  test_generated_marker_missing_fails
  test_manifest_missing_fails_when_migration_file_present
  test_check_runs_clean_on_this_worktree_skeleton
"""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
from collections.abc import Iterable
from pathlib import Path
from typing import NamedTuple

REPO_ROOT = Path(__file__).resolve().parent.parent
MANIFEST_PATH = REPO_ROOT / ".migration_manifest.json"
GENERATED_MARKER = "<!-- DO NOT EDIT: generated by hermes-skill-creator-plugin -->"
GLOB_PATTERNS = ("MIGRATION.md", "MIGRATION.hermes-patch.md", "MIGRATION.skill-port.md")


class Finding(NamedTuple):
    """One violation: file, message."""

    path: Path
    message: str


def _sha256_of(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _is_git_tracked(path: Path) -> bool:
    """True when the path is in the git index."""
    try:
        out = subprocess.check_output(
            ["git", "ls-files", "--error-unmatch", "--", str(path)],
            cwd=str(REPO_ROOT),
            stderr=subprocess.DEVNULL,
            text=True,
        )
    except (subprocess.CalledProcessError, FileNotFoundError):
        return False
    return out.strip() != ""


def _iter_migration_files(root: Path) -> list[Path]:
    out: list[Path] = []
    for pattern in GLOB_PATTERNS:
        p = root / pattern
        if p.exists():
            out.append(p)
    return out


def _load_manifest() -> dict[str, str]:
    """Load .migration_manifest.json from the worktree root. Empty on missing."""
    if not MANIFEST_PATH.exists():
        return {}
    try:
        data = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    return {str(k): str(v) for k, v in data.items() if isinstance(v, str)}


def check_migration_files(root: Path) -> list[Finding]:
    """Run all checks against every MIGRATION*.md in the worktree root."""
    findings: list[Finding] = []
    manifest = _load_manifest()
    for p in _iter_migration_files(root):
        rel = p.relative_to(root)
        # 1. Generated marker MUST be present.
        try:
            content = p.read_text(encoding="utf-8", errors="replace")
        except OSError:
            findings.append(Finding(path=p, message=f"could not read {rel}"))
            continue
        if GENERATED_MARKER not in content:
            findings.append(
                Finding(
                    path=p,
                    message=(f"{rel}: missing generated marker " f"({GENERATED_MARKER!r})"),
                )
            )
        # 2. If git-tracked, the sha256 MUST match the manifest entry.
        if _is_git_tracked(p):
            sha = _sha256_of(p)
            expected = manifest.get(str(rel))
            if expected is None:
                findings.append(
                    Finding(
                        path=p,
                        message=(
                            f"{rel} is git-tracked but missing from " f"{MANIFEST_PATH.name}; re-run the generator"
                        ),
                    )
                )
            elif sha != expected:
                findings.append(
                    Finding(
                        path=p,
                        message=(
                            f"{rel} sha256 {sha[:12]} differs from "
                            f"manifest entry {expected[:12]}; "
                            f"hand-edit detected — regenerate via the script"
                        ),
                    )
                )
    return findings


def run_all_checks(root: Path) -> list[Finding]:
    return check_migration_files(root)


def _parse_args(argv: Iterable[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    return parser.parse_args(list(argv))


def main(argv: Iterable[str] | None = None) -> int:
    if argv is None:
        argv = sys.argv[1:]
    _parse_args(argv)
    findings = run_all_checks(REPO_ROOT)
    if findings:
        for f in findings:
            print(f"[check_migration_note] FAIL: {f.message}", file=sys.stderr)
        print(
            f"[check_migration_note] {len(findings)} finding(s) — "
            f"MIGRATION*.md must be regenerated, not hand-edited.",
            file=sys.stderr,
        )
        return 1
    print("[check_migration_note] OK (all MIGRATION*.md match generator manifest)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
