"""check_migration_note.py — MIGRATION*.md files are generated, not hand-edited.
Pre-commit refuses any non-generated change to a MIGRATION*.md.
"""

# TDD test cases:
#   test_unmodified_migration_file_passes
#   test_hand_edit_to_migration_hermes_patch_md_fails
#   test_hand_edit_to_migration_skill_port_md_fails
#   test_generated_marker_present_passes
#   test_generated_marker_missing_fails
#   test_check_runs_clean_on_this_worktree_skeleton

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
GENERATED_MARKER = "<!-- DO NOT EDIT: generated by hermes-skill-creator-plugin -->"


def main() -> int:
    migrations = list(REPO_ROOT.rglob("MIGRATION*.md"))
    failures: list[str] = []
    for p in migrations:
        if ".venv" in p.parts or ".git" in p.parts:
            continue
        try:
            content = p.read_text(encoding="utf-8")
        except OSError:
            continue
        if GENERATED_MARKER not in content:
            failures.append(
                f"{p.relative_to(REPO_ROOT)}: missing generated marker ({GENERATED_MARKER!r})"
            )
    if failures:
        for line in failures:
            print(f"[check_migration_note] FAIL: {line}")
        return 1
    print("[check_migration_note] OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
