"""check_migration_note.py — MIGRATION*.md is generated, not hand-edited.

Pre-commit refuses any MIGRATION*.md whose sha256 differs from the
generator's last-emitted checksum recorded in `.migration_manifest.json`
at the worktree root. The generator (Script #1 --emit-migration-note and
the migrated-skill installer) writes BOTH the MIGRATION*.md file AND the
manifest entry on every regeneration. If a developer hand-edits the
migration note, the checksum drift is caught at commit time.

TDD test cases (mirror of tests/meta/test_meta_check_migration_note.py):

  test_unmodified_migration_file_passes
  test_hand_edit_to_migration_hermes_patch_md_fails
  test_hand_edit_to_migration_skill_port_md_fails
  test_generated_marker_present_passes
  test_generated_marker_missing_fails
  test_manifest_missing_fails_when_migration_file_present
  test_check_runs_clean_on_this_worktree_skeleton
"""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path
from typing import NamedTuple

REPO_ROOT = Path(__file__).resolve().parent.parent
MANIFEST_PATH = REPO_ROOT / ".migration_manifest.json"
GENERATED_MARKER = (
    "<!-- DO NOT EDIT: generated by hermes-skill-creator-plugin -->"
)
GLOB_PATTERNS = (
    "MIGRATION.md",
    "MIGRATION.hermes-patch.md",
    "MIGRATION.skill-port.md",
)
SHA_PREVIEW_LEN = 12  # magic number: chars shown in human messages.


class Finding(NamedTuple):
    """One violation: file, message."""

    path: Path
    message: str


def _sha256_of(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _is_git_tracked(path: Path) -> bool:
    """True when the path is in the git index."""
    try:
        out = subprocess.check_output(
            ["git", "ls-files", "--error-unmatch", "--", str(path)],
            cwd=str(REPO_ROOT),
            stderr=subprocess.DEVNULL,
            text=True,
        )
    except (subprocess.CalledProcessError, FileNotFoundError):
        return False
    return out.strip() != ""


def _iter_migration_files(root: Path) -> list[Path]:
    out: list[Path] = []
    for pattern in GLOB_PATTERNS:
        p = root / pattern
        if p.exists():
            out.append(p)
    return out


def _load_manifest() -> dict[str, str]:
    """Load manifest from worktree root; empty dict on missing/invalid."""
    if not MANIFEST_PATH.exists():
        return {}
    try:
        data = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    return {str(k): str(v) for k, v in data.items() if isinstance(v, str)}


def _check_marker(p: Path, rel: Path, content: str) -> Finding | None:
    """Return a marker-missing finding if the file lacks GENERATED_MARKER."""
    if GENERATED_MARKER in content:
        return None
    msg = f"{rel}: missing generated marker ({GENERATED_MARKER!r})"
    return Finding(path=p, message=msg)


def _check_manifest_sha(
    p: Path,
    rel: Path,
    sha: str,
    expected: str | None,
) -> Finding | None:
    """Return a manifest-drift finding if sha != expected (or missing)."""
    if expected is None:
        msg = (
            f"{rel} is git-tracked but missing from "
            f"{MANIFEST_PATH.name}; re-run the generator"
        )
        return Finding(path=p, message=msg)
    if sha != expected:
        preview_actual = sha[:SHA_PREVIEW_LEN]
        preview_expected = expected[:SHA_PREVIEW_LEN]
        msg = (
            f"{rel} sha256 {preview_actual} differs from "
            f"manifest entry {preview_expected}; "
            f"hand-edit detected — regenerate via the script"
        )
        return Finding(path=p, message=msg)
    return None


@dataclass(frozen=True)
class _CheckInputs:
    """Inputs for one migration-file check loop iteration."""

    path: Path
    rel: Path
    content: str
    manifest: dict[str, str]


def _inspect_one(inputs: _CheckInputs) -> list[Finding]:
    """Inspect one migration file and return its findings."""
    findings: list[Finding] = []
    marker = _check_marker(inputs.path, inputs.rel, inputs.content)
    if marker is not None:
        findings.append(marker)
    if not _is_git_tracked(inputs.path):
        return findings
    sha = _sha256_of(inputs.path)
    sha_finding = _check_manifest_sha(
        inputs.path,
        inputs.rel,
        sha,
        inputs.manifest.get(str(inputs.rel)),
    )
    if sha_finding is not None:
        findings.append(sha_finding)
    return findings


def check_migration_files(root: Path) -> list[Finding]:
    """Run all checks against every MIGRATION*.md in the worktree root."""
    manifest = _load_manifest()
    findings: list[Finding] = []
    for p in _iter_migration_files(root):
        rel = p.relative_to(root)
        try:
            content = p.read_text(encoding="utf-8", errors="replace")
        except OSError:
            findings.append(Finding(path=p, message=f"could not read {rel}"))
            continue
        findings.extend(_inspect_one(_CheckInputs(p, rel, content, manifest)))
    return findings


def run_all_checks(root: Path) -> list[Finding]:
    return check_migration_files(root)


def _parse_args(argv: Iterable[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    return parser.parse_args(list(argv))


def _emit(message: str) -> None:
    sys.stderr.write(message + "\n")


def _emit_ok(message: str) -> None:
    sys.stdout.write(message + "\n")


def main(argv: Iterable[str] | None = None) -> int:
    if argv is None:
        argv = sys.argv[1:]
    _parse_args(argv)
    findings = run_all_checks(REPO_ROOT)
    if findings:
        for f in findings:
            _emit(f"[check_migration_note] FAIL: {f.message}")
        summary = (
            f"[check_migration_note] {len(findings)} finding(s) — "
            f"MIGRATION*.md must be regenerated, not hand-edited."
        )
        _emit(summary)
        return 1
    ok_msg = "[check_migration_note] OK (all MIGRATION*.md match manifest)"
    _emit_ok(ok_msg)
    return 0


if __name__ == "__main__":
    sys.exit(main())